export const appearAnimationsContent = {
  aua0kh: {
    default: {
      initial: {
        opacity: 0.001,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        x: 0,
        y: 0,
      },
      animate: {
        opacity: 1,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        transition: { bounce: 0.2, delay: 1, duration: 0.4, type: "spring" },
        x: 0,
        y: 0,
      },
    },
    "14enm81": {
      initial: {
        opacity: 0.001,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        x: 0,
        y: 0,
      },
      animate: {
        opacity: 1,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        transition: { bounce: 0.2, delay: 1, duration: 0.4, type: "spring" },
        x: 0,
        y: 0,
      },
    },
    "1f0hsks": {
      initial: {
        opacity: 0.001,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        x: 0,
        y: 0,
      },
      animate: {
        opacity: 1,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        transition: { bounce: 0.2, delay: 1, duration: 0.4, type: "spring" },
        x: 0,
        y: 0,
      },
    },
  },
  "3n8mk7": {
    default: {
      initial: {
        opacity: 0.001,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        x: 0,
        y: 170,
      },
      animate: {
        opacity: 1,
        rotate: 0,
        rotateX: 0,
        rotateY: 0,
        scale: 1,
        skewX: 0,
        skewY: 0,
        transition: {
          damping: 27,
          delay: 0.72,
          mass: 0.3,
          stiffness: 121,
          type: "spring",
        },
        x: 0,
        y: 0,
      },
    },
  },
};

export const breakpoints = [
  { hash: "r0psrf", mediaQuery: "(min-width: 1200px)" },
  {
    hash: "14enm81",
    mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
  },
  { hash: "1f0hsks", mediaQuery: "(max-width: 809.98px)" },
  { hash: "128kipa", mediaQuery: "(min-width: 1200px)" },
  {
    hash: "1l0aw67",
    mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
  },
  { hash: "xwr0r7", mediaQuery: "(max-width: 809.98px)" },
];
